=== Zahra-HBB/XML-Training-Excersises/Sheriff Letter Exercise/sheriffLetters.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:shl="http://www.cote.com.au/sheriffLetter" targetNamespace="http://www.cote.com.au/sheriffLetter" elementFormDefault="qualified" attributeFormDefault="unqualified" version="http://sheriffLetter/XMLSchema/1.0">
	<xsd:element name="root">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="SheriffLetter">
					<xsd:complexType mixed="true">
						<xsd:sequence>
							<xsd:element name="Prefix" minOccurs="1">
								<xsd:simpleType>
									<xsd:restriction base="xsd:string">
										<xsd:enumeration value="Mr."/>
										<xsd:enumeration value="Ms."/>
									</xsd:restriction>
								</xsd:simpleType>
							</xsd:element>
							<xsd:element name="FirstName" type="xsd:string" minOccurs="1"/>
							<xsd:element name="LastName" type="xsd:string" minOccurs="1"/>
							<xsd:element name="MiddleName" type="xsd:string" minOccurs="0"/>
							<xsd:element name="JurorAddress" type="shl:Address" minOccurs="1"/>
							<xsd:element name="IssueDate" type="xsd:string" minOccurs="1"/>
							<xsd:element name="JurorNo" type="xsd:integer" minOccurs="1"/>
							<xsd:element name="JurorIssueCode" type="xsd:string" minOccurs="0"/>
							<xsd:element name="PreceptNo" type="xsd:integer" minOccurs="1"/>
							<xsd:element name="Juridiction" minOccurs="1">
								<xsd:simpleType>
									<xsd:restriction base="xsd:string">
										<xsd:enumeration value="GOSFORD"/>
										<xsd:enumeration value="PENRITH"/>
									</xsd:restriction>
								</xsd:simpleType>
							</xsd:element>
							<xsd:element name="JuridictionType" type="xsd:string" minOccurs="1"/>
							<xsd:element name="CourtType" minOccurs="1">
								<xsd:simpleType>
									<xsd:restriction base="xsd:string">
										<xsd:enumeration value="CRIMINAL"/>
										<xsd:enumeration value="CIVIL"/>
									</xsd:restriction>
								</xsd:simpleType>
							</xsd:element>
							<xsd:element name="CourtAddress" type="shl:Address" minOccurs="0"/>
							<xsd:element name="PanelType" minOccurs="1">
								<xsd:simpleType>
									<xsd:restriction base="xsd:string">
										<xsd:enumeration value="A PANEL"/>
										<xsd:enumeration value="B PANEL"/>
										<xsd:enumeration value="C PANEL"/>
									</xsd:restriction>
								</xsd:simpleType>
							</xsd:element>
							<xsd:element name="DateOfAttendance" type="xsd:string" minOccurs="1"/>
							<xsd:element name="DutyFromDate" type="xsd:string" minOccurs="0"/>
							<xsd:element name="DutyToDate" type="xsd:string" minOccurs="0"/>
							<xsd:element name="NoticeRefNo" type="xsd:string" minOccurs="1"/>
							<xsd:element name="SheriffOfficeAddress" minOccurs="1">
								<xsd:complexType mixed="true">
									<xsd:sequence>
										<xsd:element name="AddressType" minOccurs="1">
											<xsd:simpleType>
												<xsd:restriction base="xsd:string">
													<xsd:enumeration value="PO Box"/>
													<xsd:enumeration value="Locked Bag"/>
												</xsd:restriction>
											</xsd:simpleType>
										</xsd:element>
										<xsd:element name="NameOfBuilding" type="xsd:string" minOccurs="1"/>
										<xsd:element name="Suburb" type="xsd:string" minOccurs="1"/>
										<xsd:element name="PostCode" minOccurs="1">
											<xsd:simpleType>
												<xsd:restriction base="xsd:string">
													<xsd:pattern value="[0-9]{4}"/>
												</xsd:restriction>
											</xsd:simpleType>
										</xsd:element>
										<xsd:element name="Telephone" type="xsd:string" minOccurs="1"/>
										<xsd:element name="T.T.Y" type="xsd:string" minOccurs="1"/>
										<xsd:element name="Fax" type="xsd:string" minOccurs="1" maxOccurs="2"/>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="TypeOfLetter" minOccurs="1">
								<xsd:simpleType>
									<xsd:restriction base="xsd:string">
										<xsd:enumeration value="Failure to attend judy duty"/>
										<xsd:enumeration value="Reason of non attendance at jury duty - accepted"/>
										<xsd:enumeration value="Acknowledgement of correspondence"/>
										<xsd:enumeration value="Application to be excused from judy duty - not accepted"/>
										<xsd:enumeration value="Removal from jury roll - application declined"/>
										<xsd:enumeration value="Application to be excused from jury duty"/>
										<xsd:enumeration value="Non attendence request form"/>
										<xsd:enumeration value="Remove from draft jurt roll form"/>
									</xsd:restriction>
								</xsd:simpleType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<!-- ************************************************************************************************ -->
	<!--                                            GENERAL DEFENITIONS                                   -->
	<!-- ************************************************************************************************ -->
	<!-- Defenition of Address -->
	<xsd:complexType name="Address" mixed="true">
		<xsd:sequence>
			<xsd:element name="AddressLine1" type="xsd:string" minOccurs="1"/>
			<xsd:element name="AddressLine2" type="xsd:string" minOccurs="0"/>
			<xsd:element name="Suburb" type="xsd:string" minOccurs="1"/>
			<xsd:element name="State" minOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:pattern value="NSW|VIC|QLD|WA|SA|NT|ACT"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="PostCode" minOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:pattern value="[0-9]{4}"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>

=== Zahra-HBB/XML-Training-Excersises/Sheriff Letter Exercise/sheriffLetter-XML-Sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<shl:root xmlns:shl="http://www.cote.com.au/sheriffLetter" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.cote.com.au/sheriffLetter sheriffLetters.xsd">
	<shl:SheriffLetter>
		<shl:Prefix>Ms.</shl:Prefix>
		<shl:FirstName>NICOLE</shl:FirstName>
		<shl:LastName>PEITA</shl:LastName>
		<shl:MiddleName>HOGAN</shl:MiddleName>
		<shl:JurorAddress>
			<shl:AddressLine1>3 LAW PLACE</shl:AddressLine1>
			<shl:Suburb>BLUE HAVEN</shl:Suburb>
			<shl:State>NSW</shl:State>
			<shl:PostCode>2262</shl:PostCode>
		</shl:JurorAddress>
		<shl:IssueDate>29/05/2005</shl:IssueDate>
		<shl:JurorNo>3571969</shl:JurorNo>
		<shl:PreceptNo>50763</shl:PreceptNo>
		<shl:Juridiction>GOSFORD</shl:Juridiction>
		<shl:JuridictionType>DISTRICT</shl:JuridictionType>
		<shl:CourtType>CRIMINAL</shl:CourtType>
		<shl:PanelType>B PANEL</shl:PanelType>
		<shl:DateOfAttendance>29/08/2005</shl:DateOfAttendance>
		<shl:NoticeRefNo>1002 BLDR</shl:NoticeRefNo>
		<shl:SheriffOfficeAddress>
			<shl:AddressType>PO Box</shl:AddressType>
			<shl:NameOfBuilding>A 4</shl:NameOfBuilding>
			<shl:Suburb>Sydney South</shl:Suburb>
			<shl:PostCode>1232</shl:PostCode>
			<shl:Telephone>(02) 9209 8222</shl:Telephone>
			<shl:T.T.Y>1800 469 889</shl:T.T.Y>
			<shl:Fax>(02) 9287 7260 or (02) 9287 7222</shl:Fax>
		</shl:SheriffOfficeAddress>
		<shl:TypeOfLetter>Reason of non attendance at jury duty - accepted</shl:TypeOfLetter>
	</shl:SheriffLetter>
</shl:root>
