=== Zahra-HBB/XML-Training-Excersises/food-recipes/recipe-schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.cote.com.au/xml/recipes" 
            version="http://www.cote.com.au/xml/recipes/1.0" attributeFormDefault="unqualified" elementFormDefault="qualified">
     <xsd:element name="collection">
        <xsd:complexType mixed="true">
            <xsd:sequence>
                <xsd:element name="description" type="xsd:string" />
                <!-- RECEPIES -->
                <xsd:element name="recipes">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="recipe" >
                                <xsd:complexType mixed="true">
                                    <xsd:sequence>
                                        <!-- ID -->
                                        <xsd:element name="id" type="xsd:string" minOccurs="1" />
                                        <!-- TITLE -->
                                        <xsd:element name="title" type="xsd:string" minOccurs="1" />
                                        <!-- DATE -->
                                        <xsd:element name="date" type="xsd:date" minOccurs="1" />
                                        <!-- INGREDIENTS -->
                                        <xsd:element name="ingredients">
                                            <xsd:complexType>
                                                <xsd:sequence>
                                                    <xsd:element name="ingredient" type="ingredientInfo" minOccurs="2" maxOccurs="unbounded"/>
                                                </xsd:sequence>
                                            </xsd:complexType>
                                        </xsd:element>
                                        <!-- PREPERATION -->
                                        <xsd:element name="preparationSteps">
                                            <xsd:complexType>
                                                <xsd:sequence>
                                                    <xsd:element name="step" type="xsd:string" minOccurs="5" maxOccurs="10" />
                                                </xsd:sequence>
                                            </xsd:complexType>
                                        </xsd:element>
                                        <!-- COMMENT -->
                                        <xsd:element name="comment" type="xsd:string" minOccurs="0" />
                                        <!-- NUTRITIONS -->
                                        <xsd:element name="nutritions">
                                            <xsd:complexType>
                                                <xsd:sequence>
                                                    <xsd:element name="nutrition" minOccurs="1">
                                                        <xsd:complexType>
                                                            <xsd:sequence>
                                                                <xsd:element name="calories" type="xsd:integer" minOccurs="0" />
                                                                <xsd:element name="fat" type="nutritiousInfo" minOccurs="0" />
                                                                <xsd:element name="carbohydrates" type="nutritiousInfo" minOccurs="0" />
                                                                <xsd:element name="protein" type="nutritiousInfo" minOccurs="0" />
                                                                <xsd:element name="alcohol" type="nutritiousInfo" minOccurs="0" />
                                                            </xsd:sequence>
                                                        </xsd:complexType>
                                                    </xsd:element>
                                                </xsd:sequence>
                                            </xsd:complexType>
                                        </xsd:element>
                                        <!-- RELATED -->
                                        <xsd:element name="related" minOccurs="0">
                                            <xsd:complexType>
                                                <xsd:simpleContent>
                                                    <xsd:extension base="xsd:string">
                                                        <xsd:attribute name="ref" type="xsd:string" />
                                                    </xsd:extension>
                                                </xsd:simpleContent>
                                            </xsd:complexType>
                                        </xsd:element>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <!-- GENERAL INFO -->
    <!-- Definition of ingredientInfo type -->
    <xsd:complexType name="ingredientInfo">
        <xsd:sequence>
            <xsd:element name="name" type="xsd:string" minOccurs="1" />
            <xsd:element name="amount" type="xsd:string" minOccurs="0" />
            <xsd:element name="unit" type="xsd:string" minOccurs="0" />
        </xsd:sequence>
    </xsd:complexType>
    <!-- Definition of nutritiousInfo type -->
    <xsd:simpleType name="nutritiousInfo">
        <xsd:restriction base="xsd:integer">
            <xsd:minInclusive value="0" />
            <xsd:maxInclusive value="100" />
        </xsd:restriction>
    </xsd:simpleType>
</xsd:schema>

=== Zahra-HBB/XML-Training-Excersises/food-recipes/xml-recipe-sample.xml
<?xml version="1.0" encoding="utf-8"?>
<collection xmlns="http://www.cote.com.au/xml/recipes" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.cote.com.au/xml/recipes recipe-schema.xsd">
	<description>This is a Persian recipe</description>
	<recipes>
		<recipe>
			<id>Top1</id>
			<title>Qorme Sabzi(stew)</title>
			<date>Fri, 28 May 04</date>
			<ingredients>
				<ingredient>
					<name>Fried Vegtables</name>
					<ingredients>
						<ingredient>
							<name>mixed persian vegtables</name>
							<ingredients>
								<ingredient>
									<name>parsley</name>
									<amount>100</amount>
									<unit>grams</unit>
								</ingredient>
								<ingredient>
									<name>coriander</name>
									<amount>100</amount>
									<unit>grams</unit>
								</ingredient>
								<ingredient>
									<name>fungreek</name>
									<amount>50</amount>
									<unit>grams</unit>
								</ingredient>
								<ingredient>
									<name>persian leek</name>
									<amount>100</amount>
									<unit>grams</unit>
								</ingredient>
								<ingredient>
									<name>spinach</name>
									<amount>50</amount>
									<unit>grams</unit>
								</ingredient>
							</ingredients>
							<preparation>
								<step>Dice all vegtables together</step>
								<step>Put olive intho the pan</step>
								<step>Let the oil get hot</step>
								<step>Put vegtables into the hot oil on the low heat</step>
								<step>let them boil until their colour chenge a bit</step>
							</preparation>
						</ingredient>
					</ingredients>
				</ingredient>
				<ingredient>
					<name>lamb diced</name>
					<amount>300</amount>
					<unit>grams</unit>
				</ingredient>
				<ingredient>
					<name>onion</name>
					<amount>1</amount>
				</ingredient>
				<ingredient>
					<name>red beens</name>
					<amount>200</amount>
					<unit>grams</unit>
				</ingredient>
				<ingredient>
					<name>dried lime</name>
					<amount>3</amount>
				</ingredient>
				<ingredient>
					<name>turmeric</name>
					<amount>1.5</amount>
					<unit>tea spoon</unit>
				</ingredient>
				<ingredient>
					<name>salt</name>
					<amount>2</amount>
					<unit>tea spoon</unit>
				</ingredient>
				<ingredient>
					<name>water</name>
					<amount>2</amount>
					<unit>cups</unit>
				</ingredient>
				<ingredient>
					<name>rice</name>
					<amount>3</amount>
					<unit>cups</unit>
				</ingredient>
			</ingredients>
			<preparation>
				<step>Dice onion and put it in hot extra olive oil until it gets a caramelise colour</step>
				<step>Add turmaric to them</step>
				<step>Add meat and red beens to the onions</step>
				<step>Add water to the ingredients and let them boil slowly for 1.5 hours</step>
				<step>Add vegtables,dried limes, salt to your dish</step>
				<step>Let all ingredients boil for another 1 hour </step>
				<step>Make the rice as usuall. When the stew is ready you can have it with the rice and 
             have some persian salad or yoghurt beside your "Qorme Sabzi"</step>
			</preparation>
			<comment>Qorme Sabzi is one of the most delisious Persian foods that everyone should try it</comment>
			<nutrition>
				<calories>3520</calories>
				<fat>66%</fat>
			</nutrition>
			<related ref="QS">this goes very well with persian salad or yoghurt</related>
		</recipe>
	</recipes>
</collection>
